# Practicumopdrachten Week 3.1 (Algoritmes)

## Opdracht

1. Maak met python minimaal drie arrays van minimaal 20 willekeurige en niet gesorteerde integers (meer mag ook).
2. Zoek op internet naar ten minste drie verschillende sorteeralgoritmes die je wilt gebruiken om de integer arrays mee te sorteren.
3. Implementer je gekozen sorteeralgoritmes om de integer arrays mee te sorteren. Maak voor elk sorteeralgoritme een nieuwe methode aan die een integer array als parameter heeft en de integer array gesorteerd returnt.

*Kudos als je een moeilijk, super efficient of creatief algoritme kunt vinden óf zelfs bedenken ;*

### Package imports

In [9]:
import warnings
import numpy as np
import sqlite3
import pandas as pd
import math
warnings.simplefilter('ignore')

### Creër ungesorteerde arrays

In [5]:
array1 = np.random.randint(10, size=(20)) 
array2 = np.random.randint(10, size=(20)) 
array3 = np.random.randint(10, size=(20)) 

print(array1)
print(array2)
print(array3)

[3 2 2 2 7 0 1 9 3 0 6 8 1 4 6 4 6 0 4 2]
[8 4 8 6 7 7 6 6 1 6 3 0 3 0 5 4 5 2 7 9]
[4 9 8 3 0 4 6 1 1 7 6 2 2 0 9 3 1 2 3 5]


### Sorteer algoritme methodes

##### Shell sort

Bij Shellsort worden elementen met elkaar vergeleken dat niet direct naast elkaar, maar een stuk apart liggen. Dit algoritme werkt via de volgende manier: 
1. − Start
2. − Initialize the value of gap size. Example: h
3. − Divide the list into smaller sub-part. Each must have equal intervals to h
4. − Sort these sub-lists using insertion sort
5. – Repeat this step 2 until the list is sorted.
6. – Print a sorted list.
7. – Stop.


In [7]:
def shellSort(array):
    n = len(array)
    k = int(math.log2(n))
    interval = 2**k -1
    while interval > 0:
        for i in range(interval, n):
            temp = array[i]
            j = i
            while j >= interval and array[j - interval] > temp:
                array[j] = array[j - interval]
                j -= interval
            array[j] = temp
        k -= 1
        interval = 2**k -1
    return array

### Resultaten

In [13]:

print("SHELL SORT")
print(shellSort(array1))
print(shellSort(array2))
print(shellSort(array3))
print("-----------------")
print()


SHELL SORT
[0 0 0 1 1 2 2 2 2 3 3 4 4 4 6 6 6 7 8 9]
[0 0 1 2 3 3 4 4 5 5 6 6 6 6 7 7 7 8 8 9]
[0 0 1 1 1 2 2 2 3 3 3 4 4 5 6 6 7 8 9 9]
-----------------


### Bronnen

1. Rathore, A. S. (2023, January 22). Sorting algorithms — with Python - towards data science. Medium. https://towardsdatascience.com/sorting-algorithms-with-python-4ec7081d78a1 
2. GfG. (2023, January 10). ShellSort. GeeksforGeeks. https://www.geeksforgeeks.org/shellsort/ 